/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BaseRecipientRegistry__factory } from "./BaseRecipientRegistry__factory";
export { IRecipientRegistry__factory } from "./IRecipientRegistry__factory";
export { OptimisticRecipientRegistry__factory } from "./OptimisticRecipientRegistry__factory";
export { SimpleRecipientRegistry__factory } from "./SimpleRecipientRegistry__factory";
