/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { InitialVoiceCreditProxy } from "./InitialVoiceCreditProxy";
export type { NFTSignup } from "./NFTSignup";
export type { SignUpNFT } from "./SignUpNFT";
