/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BaseRecipientRegistry } from "./BaseRecipientRegistry";
export type { IRecipientRegistry } from "./IRecipientRegistry";
export type { OptimisticRecipientRegistry } from "./OptimisticRecipientRegistry";
export type { SimpleRecipientRegistry } from "./SimpleRecipientRegistry";
