/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as pollSol from "./Poll.sol";
export type { pollSol };
import type * as crypto from "./crypto";
export type { crypto };
import type * as gatekeepers from "./gatekeepers";
export type { gatekeepers };
import type * as initialVoiceCreditProxy from "./initialVoiceCreditProxy";
export type { initialVoiceCreditProxy };
import type * as trees from "./trees";
export type { trees };
export type { DomainObjs } from "./DomainObjs";
export type { IMACI } from "./IMACI";
export type { MACI } from "./MACI";
export type { VkRegistry } from "./VkRegistry";
