/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as constantInitialVoiceCreditProxySol from "./ConstantInitialVoiceCreditProxy.sol";
export type { constantInitialVoiceCreditProxySol };
export type { InitialVoiceCreditProxy } from "./InitialVoiceCreditProxy";
