name: Contracts-Build

on:
  push: 
    branches: [ main, dev ]
    tags: ['*']
  pull_request:


env:
  cwd: ${{github.workspace}}/packages/contracts

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  contracts-build:
    uses: ./.github/workflows/reusable-contracts-build.yml