name: Frontend-Build

on:
  workflow_call:

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --frozen-lockfile
          
      - name: Build
        run: |
          CI=false yarn workspace @qfi/hooks build
          CI=false yarn workspace @qfi/ui build
          CI=false yarn workspace @qfi/app build
